CREATE TABLE ERS_USERS (
        U_ID NUMBER (*,0) PRIMARY KEY,
        U_USERNAME VARCHAR2(40) UNIQUE,
        U_PASSWORD VARCHAR2(40),
        U_FIRSTNAME VARCHAR2(30),
        U_LASTNAME VARCHAR2(30),
        U_EMAIL VARCHAR2(100) UNIQUE,
        UR_ID NUMBER (*,0),
        FOREIGN KEY (UR_ID) REFERENCES ERS_USERS_ROLES (UR_ID) 
        )
        
CREATE TABLE ERS_USERS_ROLES (
        UR_ID NUMBER (*,0) PRIMARY KEY,
        UR_ROLE VARCHAR2(40)
    )
        
CREATE TABLE ERS_REIMBURSEMENTS (
        R_ID NUMBER (*,0) PRIMARY KEY,
        R_AMOUNT NUMBER (22,2),
        R_DESCRIPTION VARCHAR2(100),
        R_RECIEPT BLOB,
        R_SUBMITTED TIMESTAMP,
        R_RESOLVED TIMESTAMP,
        U_ID_AUTHOR NUMBER (*,0),
        U_ID_RESOLVER NUMBER (*,0),
        RT_TYPE NUMBER(*,0),
        RT_STATUS NUMBER(*,0),
        FOREIGN KEY (U_ID_AUTHOR) REFERENCES ERS_USERS (U_ID),
        FOREIGN KEY (U_ID_RESOLVER) REFERENCES ERS_USERS(U_ID),
        FOREIGN KEY (RT_STATUS)REFERENCES ERS_REIMBURSEMENT_STATUS (RS_ID),
        FOREIGN KEY (RT_TYPE) REFERENCES ERS_REIMBURSEMENT_TYPE (RT_ID)
        )

CREATE TABLE ERS_REIMBURSEMENT_STATUS (
        RS_ID NUMBER (*,0) PRIMARY KEY,
        RS_STATUS VARCHAR2(30)
        )
CREATE TABLE ERS_REIMBURSEMENT_TYPE (
        RT_ID NUMBER (*,0) PRIMARY KEY,
        RT_TYPE VARCHAR2(30)
        )

CREATE SEQUENCE ERS_USERS_U_ID_SEQ
INCREMENT BY 1
START WITH 20;
CREATE SEQUENCE USER_ROLES_UR_ID_SEQ
INCREMENT BY 1
START WITH 1;

CREATE SEQUENCE REIMBURSEMENTS_R_ID_SEQ
INCREMENT BY 1
START WITH 100;

CREATE SEQUENCE REIMBURSEMENT_STATUS_RS_ID_SEQ
INCREMENT BY 1
START WITH 200;

CREATE SEQUENCE REIMBURSEMENT_TYPE_RT_ID_SEQ
INCREMENT BY 1
START WITH 50;


CREATE OR REPLACE TRIGGER ERS_USERS_U_ID_TRIG BEFORE INSERT ON ERS_USERS FOR EACH ROW
BEGIN
    :NEW.U_ID := ERS_USERS_U_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER USER_ROLES_ID_TRIG BEFORE INSERT ON ERS_USERS_ROLES FOR EACH ROW
BEGIN
    :NEW.UR_ID := USER_ROLES_UR_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER REIMBURSEMENTS_R_ID_TRIG BEFORE INSERT ON ERS_REIMBURSEMENTS FOR EACH ROW
BEGIN
    :NEW.R_ID := REIMBURSEMENTS_R_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER REIMB_STATUS_RS_ID_TRIG BEFORE INSERT ON ERS_REIMBURSEMENT_STATUS FOR EACH ROW
BEGIN
    :NEW.RS_ID := REIMBURSEMENT_TYPE_RT_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER REIMB_TYPE_RT_ID_TRIG BEFORE INSERT ON ERS_REIMBURSEMENT_TYPE FOR EACH ROW
BEGIN
    :NEW.RT_ID := REIMBURSEMENT_STATUS_RS_ID_SEQ.NEXTVAL;
END;
/

INSERT INTO ERS_USERS_ROLES VALUES (USER_ROLES_UR_ID_SEQ.NEXTVAL, 'AUTHOR' );
INSERT INTO ERS_USERS_ROLES VALUES (USER_ROLES_UR_ID_SEQ.NEXTVAL, 'AUTHOR');
INSERT INTO ERS_USERS_ROLES VALUES (USER_ROLES_UR_ID_SEQ.NEXTVAL, 'AUTHOR');
INSERT INTO ERS_USERS_ROLES VALUES (USER_ROLES_UR_ID_SEQ.NEXTVAL, 'AUTHOR');
INSERT INTO ERS_USERS_ROLES VALUES (USER_ROLES_UR_ID_SEQ.NEXTVAL, 'RESOLVER');
INSERT INTO ERS_USERS_ROLES VALUES (USER_ROLES_UR_ID_SEQ.NEXTVAL, 'RESOLVER');
INSERT INTO ERS_USERS_ROLES VALUES (USER_ROLES_UR_ID_SEQ.NEXTVAL, 'RESOLVER');
INSERT INTO ERS_USERS_ROLES VALUES (USER_ROLES_UR_ID_SEQ.NEXTVAL, 'RESOLVER');
INSERT INTO ERS_USERS_ROLES VALUES (USER_ROLES_UR_ID_SEQ.NEXTVAL, 'AUTHOR');
INSERT INTO ERS_USERS_ROLES VALUES (USER_ROLES_UR_ID_SEQ.NEXTVAL, 'ADMIN');

INSERT INTO ERS_USERS (U_ID, U_USERNAME, U_PASSWORD, U_FIRSTNAME, U_LASTNAME, U_EMAIL) VALUES (ERS_USERS_U_ID_SEQ.NEXTVAL,'burkel','UNS92JOB6DS','Lane','Burke','a@leoin.ca');
INSERT INTO ERS_USERS VALUES (ERS_USERS_U_ID_SEQ.NEXTVAL,'Garrison','SEX16RMP9WS','Quintessa','Hunt','non.justo@ad.com', 22);
INSERT INTO ERS_USERS VALUES (ERS_USERS_U_ID_SEQ.NEXTVAL,'Kylee','WZW81SEI3UU','Sara','Conner','ac.ipsum@Phasellusvitaemauris.co.uk', 23);
INSERT INTO ERS_USERS VALUES (ERS_USERS_U_ID_SEQ.NEXTVAL,'Philip','OLX41JYM0WD','Richard','Kane','amet.massa@facilisisSuspendisse.ca',24);
INSERT INTO ERS_USERS VALUES (ERS_USERS_U_ID_SEQ.NEXTVAL,'Reese','KXR92MHU1VM','Blythe','Rowland','Curabitur@pharetra.ca',25);
INSERT INTO ERS_USERS VALUES (ERS_USERS_U_ID_SEQ.NEXTVAL,'Hunter','GKV75RTQ8VP','Buffy','Hebert','lacinia.orci.consectetuer@arcuimperdiet.co.uk',26);
INSERT INTO ERS_USERS VALUES (ERS_USERS_U_ID_SEQ.NEXTVAL,'Illiana','YCN59FQR3OG','Ian','Hood','dui.Cum.sociis@dolor.org',27);
INSERT INTO ERS_USERS VALUES (ERS_USERS_U_ID_SEQ.NEXTVAL,'Brett','AIF60DVR5MA','Kirestin','Rodriguez','per.conubia@PhasellusnullaInteger.edu',28);
INSERT INTO ERS_USERS VALUES (ERS_USERS_U_ID_SEQ.NEXTVAL,'Kieran','IZL32SBT7UT','Macaulay','Davenport','Nulla@etcommodo.net',29);
INSERT INTO ERS_USERS VALUES (ERS_USERS_U_ID_SEQ.NEXTVAL,'Cameran','LAY61YMG9OA','Venus','Hoover','Integer@Innec.co.uk',30);



