CREATE TABLE USERS (
USERID NUMBER PRIMARY KEY,
USER_ROLE VARCHAR2(10),
USERNAME VARCHAR(50),
PW VARCHAR(50),
SEC_Q1 VARCHAR(200),
SEC_A1 VARCHAR(200),
SEC_Q2 VARCHAR(200),
SEC_A2 VARCHAR(200),
SEC_Q3 VARCHAR(200),
SEC_A3 VARCHAR(200)
);

--CREATE CONSTRAINTS SEPARATELY!! IT WILL BE MORE TIME-CONSUMING BUT ULTIMATELY CLEANER!!!

CREATE TABLE CUSTOMER (
USERID NUMBER PRIMARY KEY,
SALUTATION VARCHAR2(5),
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
STREET_ADDRESS VARCHAR(50),
APT_SUITE VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50),
ZIP_CODE VARCHAR(12),
EMAIL VARCHAR(100),
SECONDARY_EMAIL VARCHAR(100),
ACCOUNTS NUMBER
);

CREATE TABLE ACCOUNTS (
ACCOUNTID NUMBER PRIMARY KEY,
ACCOUNT_TYPE VARCHAR(50),
ACCOUNT# NUMBER,
ROUTING# NUMBER,
CURR_BAL NUMBER,
TX_HIST NUMBER
);

CREATE TABLE CUSTOMER_ACCOUNTS (
USERID NUMBER,
ACCOUNTID NUMBER,
PRIMARY KEY(USERID,ACCOUNTID)
);

CREATE TABLE TRANSACTIONS (
TXID NUMBER PRIMARY KEY,
TX_TYPE VARCHAR(50),
ACCOUNTID NUMBER,
INIT_BAL NUMBER,
TX_AMT NUMBER,
FIN_BAL NUMBER
);

CREATE TABLE ACCOUNTS_TRANSACTIONS (
ACCOUNTID NUMBER,
TXID NUMBER,
PRIMARY KEY(ACCOUNTID,TXID)
);


--CREATE SEQUENCES AND TRIGGERS TO CREATE PKs

CREATE SEQUENCE SQ_PK_USERID
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_PK_ACCOUNTID
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_PK_TXID
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER GENERATE_USERID
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    SELECT SQ_PK_USERID.NEXTVAL INTO :NEW.USERID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER GENERATE_ACCOUNTID
BEFORE INSERT ON ACCOUNTS
FOR EACH ROW
BEGIN
    SELECT SQ_PK_ACCOUNTID.NEXTVAL INTO :NEW.ACCOUNTID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER GENERATE_TXID
BEFORE INSERT ON TRANSACTIONS
FOR EACH ROW
BEGIN
    SELECT SQ_PK_TXID.NEXTVAL INTO :NEW.TXID FROM DUAL;
END;



--INSERT ENTRIES INTO TABLES
--ESTABLISH CONSTRAINTS ON FKs, CHECK NOT NULLS, UNIQUES, ETC
    --FOREIGN KEYS
ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_USERID FOREIGN KEY(USERID) REFERENCES USERS(USERID);

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_ACCOUNTID FOREIGN KEY(ACCOUNTs) REFERENCES ACCOUNTS(ACCOUNTID)
ON DELETE SET NULL;

ALTER TABLE ACCOUNTS
ADD CONSTRAINT FK_TX_HIST FOREIGN KEY(TX_HIST) REFERENCES TRANSACTIONS(TXID);

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT FK_ACCT_ID FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNTS(ACCOUNTID);

ALTER TABLE CUSTOMER_ACCOUNTS
ADD CONSTRAINT COMP_PK_USERID FOREIGN KEY(USERID) REFERENCES USERS(USERID);

ALTER TABLE CUSTOMER_ACCOUNTS
ADD CONSTRAINT COMP_PK_ACCOUNTID FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNTS(ACCOUNTID);

ALTER TABLE ACCOUNTS_TRANSACTIONS
ADD CONSTRAINT COMP_PK_ACCTID FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNTS(ACCOUNTID);

ALTER TABLE ACCOUNTS_TRANSACTIONS
ADD CONSTRAINT COMP_PK_TXID FOREIGN KEY(TXID) REFERENCES TRANSACTIONS(TXID);

--INSERT INTO USERS (USER_ROLE, USERNAME, PW, SEC_Q1, SEC_A1, SEC_Q2, SEC_A2, SEC_Q3, SEC_A3) VALUES('','','','','','','','','');
INSERT INTO USERS (USER_ROLE, USERNAME, PW, SEC_Q1, SEC_A1, SEC_Q2, SEC_A2, SEC_Q3, SEC_A3) VALUES('Customer','jbanks08','mybank123','What was the name of your high school?','Russel Hodges High','What was the name of your first pet?','Spot','What city were you born in?','Milwaukee');
INSERT INTO USERS (USER_ROLE, USERNAME, PW, SEC_Q1, SEC_A1, SEC_Q2, SEC_A2, SEC_Q3, SEC_A3) VALUES('Customer','TheresaC86','gr8Day','What is your maiden name?','Franklin','What was the first name of your high school prom date?','Peter','What was the name of your kindergarten teacher?','Mr. Wilson');

--INSERT INTO CUSTOMER (SALUTATION, STREET_ADDRESS, APT_SUITE, CITY, STATE, ZIP_CODE, EMAIL, SECONDARY_EMAIL) VALUES ('','','','','',,'','');
INSERT INTO CUSTOMER (USERID, SALUTATION, FIRSTNAME, LASTNAME, STREET_ADDRESS, APT_SUITE, CITY, STATE, ZIP_CODE, EMAIL, SECONDARY_EMAIL) VALUES ('21','Mr.','Jasper','Banks','4973 Pierce Lane','','Toledo','Ohio',43654,'jbanks08@hotmail.com','jasperb@gmail.com');
INSERT INTO CUSTOMER (USERID, SALUTATION, FIRSTNAME, LASTNAME, STREET_ADDRESS, APT_SUITE, CITY, STATE, ZIP_CODE, EMAIL, SECONDARY_EMAIL) VALUES ('22','Ms.','Theresa','Cotter','83 Pepraine Rd','','Franklin','Tennessee',37012,'tcotter@gmail.com','theresa_c@yahoo.com');

--INSERT INTO ACCOUNTS (ACCOUNT_TYPE, ACCOUNT#, ROUTING#, CURR_BAL) VALUES('','','','');
INSERT INTO ACCOUNTS (ACCOUNT_TYPE, ACCOUNT#, ROUTING#, CURR_BAL) VALUES('Checking',522982889,980254056,213.56);
INSERT INTO ACCOUNTS (ACCOUNT_TYPE, ACCOUNT#, ROUTING#, CURR_BAL) VALUES('Savings',571792510,285211916,987.29);
INSERT INTO ACCOUNTS (ACCOUNT_TYPE, ACCOUNT#, ROUTING#, CURR_BAL) VALUES('Checking',607246239,762751035,782.11);
INSERT INTO ACCOUNTS (ACCOUNT_TYPE, ACCOUNT#, ROUTING#, CURR_BAL) VALUES('Savings',781035008,120753753,2961.30);

--INSERT INTO TRANSACTIONS (TX_TYPE, INIT_BAL, TX_AMT, FIN_BAL) VALUES('',,,);
INSERT INTO TRANSACTIONS (TX_TYPE, INIT_BAL, TX_AMT, FIN_BAL) VALUES('Withdrawal',902.11,120.00,782.11);
INSERT INTO TRANSACTIONS (TX_TYPE, INIT_BAL, TX_AMT, FIN_BAL) VALUES('Deposit',2616.30,345.00,2961.30);
INSERT INTO TRANSACTIONS (TX_TYPE, INIT_BAL, TX_AMT, FIN_BAL) VALUES('Withdrawal',253.56,40.00,213.56);
INSERT INTO TRANSACTIONS (TX_TYPE, INIT_BAL, TX_AMT, FIN_BAL) VALUES('Withdrawal',1147.29,160.00,987.29);

--INSERT FOREIGN KEY VALUES
ALTER TABLE ACCOUNTS
DROP COLUMN TX_HIST;

ALTER TABLE ACCOUNTS
ADD COLUMN TX_HIST NUMBER,
FOREIGN KEY(TX_HIST) REFERENCES ACCOUNTS_TRANSACTIONS(PRIMARY KEY);




