CREATE TABLE EMPLOYEES (
EMPLID NUMBER PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL,
PW VARCHAR(30) NOT NULL,
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
MANAGER VARCHAR(5) NOT NULL
);

CREATE TABLE REIMBURSEMENTS (
R_ID NUMBER PRIMARY KEY,
AMOUNT NUMBER NOT NULL,
DESCRIPTION VARCHAR(200) NOT NULL,
RECEIPT BLOB,
SUBMITTED TIMESTAMP,
AUTHOR NUMBER NOT NULL,
STATUS VARCHAR(20) NOT NULL,
RECONCILED TIMESTAMP,
ARBITRATOR NUMBER NOT NULL
);

CREATE SEQUENCE ERS_SQ_PK_EMPLID 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE ERS_SQ_PK_R_ID
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ERS_GENERATE_EMPLID
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
    SELECT ERS_SQ_PK_EMPLID.NEXTVAL INTO :NEW.EMPLID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER ERS_GENERATE_R_ID
BEFORE INSERT ON REIMBURSEMENTS
FOR EACH ROW
BEGIN
    SELECT ERS_SQ_PK_R_ID.NEXTVAL INTO :NEW.R_ID FROM DUAL;
END;

ALTER TABLE REIMBURSEMENTS
ADD CONSTRAINT FK_AUTHOR FOREIGN KEY(AUTHOR) REFERENCES EMPLOYEES(EMPLID);

ALTER TABLE REIMBURSEMENTS
ADD CONSTRAINT FK_RESOLVER FOREIGN KEY(ARBITRATOR) REFERENCES EMPLOYEES(EMPLID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT U_EMPLOYEE UNIQUE (USERNAME, EMAIL);

INSERT INTO EMPLOYEES (USERNAME, PW, FIRSTNAME, LASTNAME, EMAIL, MANAGER) VALUES('TFranklin','paymeback','Theresa','Franklin','tfranklin@company.com','NO');
INSERT INTO EMPLOYEES (USERNAME, PW, FIRSTNAME, LASTNAME, EMAIL, MANAGER) VALUES('CherylA321','paymeback','Cheryl','Anderson','canderson@company.com','YES');
INSERT INTO EMPLOYEES (USERNAME, PW, FIRSTNAME, LASTNAME, EMAIL, MANAGER) VALUES('RH113','paymeback','Roger','Hines','rhines@company.com','YES');
INSERT INTO EMPLOYEES (USERNAME, PW, FIRSTNAME, LASTNAME, EMAIL, MANAGER) VALUES('CJackson','paymeback','Colin','Jackson','cjackson@company.com','NO');
INSERT INTO EMPLOYEES (USERNAME, PW, FIRSTNAME, LASTNAME, EMAIL, MANAGER) VALUES('hot2trot86','paymebackNOW!','Sarah','Trottsky','strottsky@company.com','NO');
INSERT INTO EMPLOYEES (USERNAME, PW, FIRSTNAME, LASTNAME, EMAIL, MANAGER) VALUES('LewisW','paymeback','Lewis','Williams','lwilliams@company.com','NO');

INSERT INTO REIMBURSEMENTS (AMOUNT, DESCRIPTION, STATUS, SUBMITTED, AUTHOR, RECONCILED, ARBITRATOR) VALUES(200.00,'Adobe Suite Subscription Feb 2017-May 2017','Approved',TO TIMESTAMP('',),,('' TO TIMESTAMP),);

INSERT INTO REIMBURSEMENTS (AMOUNT, DESCRIPTION, STATUS, SUBMITTED, AUTHOR, RECONCILED, ARBITRATOR) VALUES(45.00,'Taxi to Business Lunch 18-May-2017','Denied',TO_TIMESTAMP('',),,TO_TIMESTAMP('',),);

INSERT INTO REIMBURSEMENTS (AMOUNT, DESCRIPTION, STATUS, SUBMITTED, AUTHOR, RECONCILED, ARBITRATOR) VALUES(,'','Approved',TO_TIMESTAMP('',),,TO_TIMESTAMP('',),);

INSERT INTO REIMBURSEMENTS (AMOUNT, DESCRIPTION, STATUS, SUBMITTED, AUTHOR, RECONCILED, ARBITRATOR) VALUES(,'','Pending',('' TO TIMESTAMP),,TO_TIMESTAMP('',),);

INSERT INTO REIMBURSEMENTS (AMOUNT, DESCRIPTION, STATUS, SUBMITTED, AUTHOR, RECONCILED, ARBITRATOR) VALUES(,'','Submitted',('' TO TIMESTAMP),,TO_TIMESTAMP('',),);

begin
    DBMS_OUTPUT.PUT_LINE(TO_TIMESTAMP ('10-MAY-2017 10:18:38', 'DD-MON-YYYY HH:MI:SS'));
end;



