DROP TABLE EMPLOYEE; 

DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT( 
DEPARTMENT_ID NUMBER PRIMARY KEY, 
DEPARTMENT_NAME VARCHAR2(200) NOT NULL);



CREATE TABLE EMPLOYEE(
EMPLOYEE_ID NUMBER PRIMARY KEY, 
EMP_FIRSTNAME VARCHAR(200) NOT NULL, 
EMP_LASTNAME VARCHAR(200) NOT NULL, 
SALARY NUMBER, 
EMP_EMAIL VARCHAR(200),
DEPARTMENT_ID NUMBER NOT NULL
CONSTRAINT FK_DEPT_EMP REFERENCES DEPARTMENT(DEPARTMENT_ID));



--Create a sequence and trigger to auto-generate primary key values for both tables. 



CREATE SEQUENCE SEQUENCE_PRIMKEY_DEPTPARTMENT

START WITH 200

INCREMENT BY 4;



CREATE SEQUENCE SEQUENCE_PRIMKEY_EMP

START WITH 3000

INCREMENT BY 3;

-- CEATE TRIGGER

CREATE OR REPLACE TRIGGER TRIG_INSERT_DEPT

BEFORE INSERT ON DEPARTMENT

FOR EACH ROW

BEGIN

    SELECT SEQUENCE_PRIMKEY_DEPTPARTMENT.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM DUAL;

END;

-- CREATE OR INSERT TRIGGER FOR EMPLOYEE
CREATE OR REPLACE TRIGGER TRIG_INSERT_EMP

BEFORE INSERT ON EMPLOYEE

FOR EACH ROW

BEGIN

    SELECT SEQUENCE_PRIMKEY_EMP.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;

END;

-- Insert at least six employees and three departments. 

INSERT INTO DEPARTMENT(DEPARTMENT_NAME) VALUES ('SHOP1');

INSERT INTO DEPARTMENT(DEPARTMENT_NAME) VALUES ('SHOP2');

INSERT INTO DEPARTMENT(DEPARTMENT_NAME) VALUES ('SHOP3');

COMMIT;



INSERT INTO EMPLOYEES(EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL,DEPARTMENT_ID)

VALUES ('JENNY', 'LYNN', 30000, 'JL@COMPANY.COM', 400);



INSERT INTO EMPLOYEES(EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL,DEPARTMENT_ID)

VALUES ('LOVELY', 'VYNN', 50000, 'LV@COMPANY.COM', 401);



INSERT INTO EMPLOYEES(EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL,DEPARTMENT_ID)

VALUES ('F_EMP3', 'L_EMP3', 60000, 'FL@COMPANY.COM', 403);



INSERT INTO EMPLOYEES(EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL,DEPARTMENT_ID)

VALUES ('F_E,P4', 'L_E4', 70000, 'FL3@COMPANY.COM', 404);





INSERT INTO EMPLOYEES(EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL,DEPARTMENT_ID)

VALUES ('F_E5', 'L_E5', 85000, 'FL5COMPANY.COM', 405);



INSERT INTO EMPLOYEES(EMP_FIRSTNAME, EMP_LASTNAME, SALARY, EMP_EMAIL,DEPARTMENT_ID)

VALUES ('F_E6', 'L6', 900, 'FL6@COMPANY.COM', 406);

END;



--CHECK ENTRIES

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;






