CREATE TABLE EMPLOYEE (
EMPLYOEE_ID INTEGER PRIMARY KEY NOT NULL,
EMPL_FRISTNAME VARCHAR2(20 BYTE) NOT NULL,
EMP_LASTNAME VARCHAR2(20 BYTE) NOT NULL,
DEPARTMENT_ID INTEGER,
SALARY INTEGER,
EMP_EMAIL VARCHAR2(20 BYTE)
);

DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
DEPARTMENT_ID INTEGER NOT NULL,
DEPARTMENT_NAME VARCHAR2(20 BYTE)NOT NULL
);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT EMPLOYEE_ID;

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_ID
FOREIGN KEY (DEPARTMENT_ID) REFERENCES EMPLOYEE(DEPARTMENT_ID);
    
CREATE SEQUENCE EMPL_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE DEP_SEQ 
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER EMP_TRIGGER
BEFORE INSERT ON EMPLYOEE
BEGIN
	SELECT EMP_SEQ.NEXVAL INTO :new.EMPLOYEE_ID
	FROM DUAL ;
END;

CREATE OR REPLACE TRIGGER DEP_TRIGGER
BEFORE INSERT ON DEPARTMENT
BEGIN
	SELECT DEP_SEQ.NEXVAL INTO :new.DEPARTMENT_ID
	FROM DUAL ;
END;

INSERT INTO EMPLOYEE VALUES (1, 'Massiel', 'Pimentel', 'Sales', 3, 20, 'massiel@gmail.com');

INSERT INTO DEPARTMENT VALUES ();
