CREATE TABLE EMPLOYEE (
   EMPLOYEE_ID VARCHAR2(20),
   EMP_FIRSTNAME VARCHAR2(50),
    EMP_LASTNAME VARCHAR2(50),
    DEPARTMENT_ID VARCHAR2(20),
    SALARY NUMBER ,
    EMP_EMAIL VARCHAR2 (20),
     CONSTRAINT EMPLOYEE_ID PRIMARY KEY ( EMPLOYEE_ID )
     CONSTRAINT DEPARTMENT_ID foreign  KEY ( department_ID );
    
      CREATE TABLE DEPARTMENT (
       DEPARTMENT_ID VARCHAR2(20),
   DEPARTMENT_NAME  VARCHAR2(50),
   EMPLOYEE_ID VARCHAR2 (20),
   CONSTRAINT EMPLOYEE_ID foreign  KEY ( EMPLOYEE_ID ),
      CONSTRAINT DEPARTMENT_ID PRIMARY KEY (DEPARTMENT_ID) );
      
      CREATE SEQUENCE EMPLOYEE_PK
  START WITH 1
  INCREMENT BY 1;
  
  CREATE SEQUENCE DEPARTMENT
  START WITH 1
  INCREMENT BY 1;
  
  INSERT INTO EMPLOYEE VALUES ( 1, 'ALYMA', 'KOUROUMA', 2, 5000, 'mina@yahoo.fr');
 
  INSERT INTO EMPLOYEE VALUES ( 2,'BRIGITTE', 'MAMY', 3, 7000, 'oscar@yahoo.fr');
 INSERT INTO EMPLOYEE VALUES ( 3,'karl', 'walker', 1, 7000, 'karl@yahoo.fr');
  INSERT INTO EMPLOYEE VALUES ( 4,'chris', 'hallway', 0, 7000, 'chris@yahoo.fr');
  INSERT INTO EMPLOYEE VALUES ( 5,'winston', 'lau', 1, 7000, 'lau@yahoo.fr');
  INSERT INTO EMPLOYEE VALUES ( 6,'simon', 'lau', 3, 7000, 'slau@yahoo.fr');
  
  INSERT INTO DEPARTMENT VALUES (1, ' IT ', 2 ) ;
  

  