--CREATE A DATABASE WITH TWO TABLES

CREATE TABLE "DEPARTMENT" (
DEPARTMENT_ID NUMBER PRIMARY KEY,
DEPARTMENT_NAME VARCHAR2(20)
);

CREATE TABLE "EMPLOYEE" (
EMPLOYEE_ID NUMBER PRIMARY KEY,
EMP_FIRSTNAME VARCHAR2(50),
EMP_LASTNAME VARCHAR2(50),
DEPARTMENT_ID NUMBER,
FOREIGN KEY(DEPARTMENT_ID) REFERENCES DEPARTMENT(DEPARTMENT_ID),
SALARY NUMBER DEFAULT 30000,
EMP_EMAIL VARCHAR2(50)
);


--CREATE PK SEQUENCES
CREATE SEQUENCE SQ_EMPLOYEE_PK
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE SQ_DEPARTMENT_PK
START WITH 1
INCREMENT BY 1;

--TRIGGER PK SEQUENCES FOR EACH NEW ENTRY
CREATE OR REPLACE TRIGGER ASSIGN_EMPLOYEE_PK
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_EMPLOYEE_PK.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER ASSIGN_DEPARTMENT_PK
BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
BEGIN
    SELECT SQ_DEPARTMENT_PK.NEXTVAL INTO :NEW.DEPARTMENT_ID FROM DUAL;
END;

--ADD ENTRIES TO EACH TABLE
INSERT INTO DEPARTMENT VALUES('IT Staff');
INSERT INTO DEPARTMENT VALUES('Sales');
INSERT INTO DEPARTMENT VALUES('Administration');
INSERT INTO DEPARTMENT VALUES('Customer Service');

INSERT INTO EMPLOYEE VALUES('Sally','Hendrix',42000,'sallyh@company.com');
INSERT INTO EMPLOYEE VALUES('Jamison','Gringle',42000,'jgringle@company.com');
INSERT INTO EMPLOYEE VALUES('Gregory','Hinds',46000,'greghinds@company.com');
INSERT INTO EMPLOYEE VALUES('Hillary','Best',46000,'hbest@company.com');
INSERT INTO EMPLOYEE VALUES('Brendan','Malone',DEFAULT,'bmalone@company.com');
INSERT INTO EMPLOYEE VALUES('Shirley','Wellington',50000,'swellington@company.com');

--CREATE STORED PROCEDURE SP_GIVE_RAISE
CREATE OR REPLACE STORED PROCEDURE SP_GIVE_RAISE()
--I know I'd want to create a loop that would iterate through each employee entry and execute the function to 
--increase the salary by 10%, but I don't quite recall how to make that happen and I'm out of time. Will study 
--and practice! Thanks again for the extension!
