conn chinook/p4ssw0rd

/* SECTION 2 */
SELECT * FROM EMPLOYEE; 

SELECT * FROM EMPLOYEE
WHERE LASTNAME = 'King';

SELECT * FROM EMPLOYEE
WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;

SELECT * FROM ALBUM
ORDER BY TITLE DESC;

SELECT FIRSTNAME FROM CUSTOMER
ORDER BY CITY ASC;

INSERT INTO GENRE VALUES (26, 'Punk Rock');

INSERT INTO GENRE VALUES (27, 'Indie Rock');

INSERT INTO EMPLOYEE VALUES(9,'Miller','Jenny','Sales Support Agent',1,'10-Oct-1984','18-JUN-04','5345 Bowness Road NW','Calgary','Canada','AB','T3B 1X9','1 (780) 878-46773', '1 (780) 676-3224', 'jenny@chinookcorp.com');
INSERT INTO EMPLOYEE VALUES(10,'Hinrichs','William','IT Staff',1,'21-Dec-1972','23-NOV-04','78 23 ST','Lethbridge','Canada','AB','T1K 5P4','+1 (403) 782-7897', '1 (403) 234-3458', 'william@chinookcorp.com');

INSERT INTO CUSTOMER VALUES(60, 'Giselle', 'Baker',null,'1012 56TH ST', 'Copenhagen', null, 'Denmark',1724, '+453 4329 3794', null, 'giselle.baker@jubii.dk',4);
INSERT INTO CUSTOMER VALUES(61, 'Pablo', 'Torres','Riotur','Praça Pio V, 234', 'Rio de Janeiro', 'RJ', 'Brazil',20040-012, '+55 (21) 3480-3452', '+55 (21) 3480-3472', 'ptorres@uol.com.br',3);

UPDATE CUSTOMER 
SET FIRSTNAME = 'Robert', LASTNAME = 'Walter'
WHERE FIRSTNAME = 'Aaron' AND LASTNAME = 'Mitchell';

UPDATE CUSTOMER 
SET FIRSTNAME = 'Robert', LASTNAME = 'Walter'
WHERE FIRSTNAME = 'Aaron' AND LASTNAME = 'Mitchell';

UPDATE CUSTOMER 
SET FIRSTNAME = 'Robert', LASTNAME = 'Walter'
WHERE FIRSTNAME = 'Aaron' AND LASTNAME = 'Mitchell';

UPDATE ARTIST 
SET NAME = 'CCR'
WHERE NAME = 'Creedence Clearwater Revival';

SELECT * 
FROM INVOICE 
WHERE BILLINGADDRESS LIKE 'T%';

SELECT * 
FROM INVOICE 
WHERE TOTAL BETWEEN 15 AND 50;

SELECT * 
FROM EMPLOYEE
WHERE HIREDATE BETWEEN '01-JUN-03' AND '01-MAR-04'; 

DELETE
FROM CUSTOMER 
WHERE FIRSTNAME = 'Robert' AND LASTNAME = 'Walter';
--ORA-02292: integrity constraint (CHINOOK.FK_INVOICECUSTOMERID) violated - child record found

DELETE 
FROM INVOICE 
WHERE CUSTOMERID = 32;
--ORA-02292: integrity constraint (CHINOOK.FK_INVOICELINEINVOICEID) violated - child record found

/* SECTION 7 */
SELECT CUSTOMER.FIRSTNAME, INVOICE.INVOICEID
FROM CUSTOMER
INNER JOIN INVOICE ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID;

SELECT CUSTOMER.CUSTOMERID, CUSTOMER.FIRSTNAME, CUSTOMER.LASTNAME, INVOICE.INVOICEID, INVOICE.TOTAL
FROM CUSTOMER
FULL OUTER JOIN INVOICE ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID;

SELECT ALBUM.TITLE, ARTIST.NAME
FROM ALBUM
RIGHT JOIN ARTIST ON ALBUM.ARTISTID = ARTIST.ARTISTID;

SELECT * 
FROM ALBUM
CROSS JOIN ARTIST
ORDER BY ARTIST.NAME ASC;

SELECT * 
FROM EMPLOYEE E1
JOIN EMPLOYEE E2 ON E1.REPORTSTO = E2.REPORTSTO;

/* SECTION 3 */

CREATE OR REPLACE FUNCTION GET_CURRENT_TIME
RETURN VARCHAR2
IS 
Z VARCHAR2(200);
BEGIN
    Z :=  to_char(CURRENT_TIMESTAMP,'DD-MON-YYYY HH24:MI:SS.FF');

    RETURN Z;
END;

BEGIN 
    DBMS_OUTPUT.PUT_LINE(GET_CURRENT_TIME());
END;

CREATE OR REPLACE FUNCTION NAME_LENGTH(N IN VARCHAR2) 
RETURN NUMBER
IS
Z INTEGER;
BEGIN
    Z:= LENGTH(N);
    RETURN Z;
END;

SELECT MEDIATYPE.*, NAME_LENGTH(NAME) FROM MEDIATYPE;


CREATE OR REPLACE FUNCTION AVERAGE_TOTAL_INVOICES
RETURN NUMBER
IS 
Z NUMBER;
BEGIN
    SELECT AVG(I.TOTAL) INTO Z FROM INVOICE I;
    DBMS_OUTPUT.PUT_LINE(Z);

    RETURN Z;
END;

BEGIN 
    DBMS_OUTPUT.PUT_LINE(AVERAGE_TOTAL_INVOICES());
END;

CREATE OR REPLACE FUNCTION MOST_EXPENSIVE_TRACK
RETURN NUMBER
IS 
Z NUMBER;
BEGIN
    SELECT MAX(T.UNITPRICE) INTO Z FROM TRACK T; 
    RETURN Z;
END;


BEGIN 
    DBMS_OUTPUT.PUT_LINE(MOST_EXPENSIVE_TRACK());
END;
